/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseCard: typeof import('./components/BaseCard.vue')['default']
    BaseInput: typeof import('./components/BaseInput.vue')['default']
    BaseSelect: typeof import('./components/BaseSelect.vue')['default']
    BaseTable: typeof import('./components/BaseTable.vue')['default']
    Breadcrumb: typeof import('./components/Breadcrumb.vue')['default']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    Header: typeof import('./components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
  }
}
